name: wp-support
recipe: wordpress
config:
  webroot: .
  xdebug: true
  database: mariadb
  php: "8.1"
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
tooling:
  composer:
    service: appserver
proxy:
    pma:
      - pma-wp-support.lndo.site
    mailhog:
      - mailhog-wp-support.lndo.site
